spring:
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE_NAME}:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}

jwt:
  secret: ${JWT_SECRET}


frontend:
  endpoint: ${FRONTEND_ENDPOINT}



